[package]
name = "auralis-core"
version = "0.1.0"
edition = "2021"

[dependencies]
pipewire = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
